// One game per date (YYYY-MM-DD); this file is also the history of every past game.
// Each game is 5 prompts. Each answer is worth 2-20 yards (rarer = more yards).
// Optional "aliases" are other accepted spellings. A unique last name is accepted automatically.
const GAMES = {
  "2026-09-28": [
    {
      prompt: "Name a franchise that has never won a Super Bowl (through Super Bowl LIX).",
      answers: [
        { name: "Arizona Cardinals", yards: 20, aliases: ["Cardinals", "Arizona"] },
        { name: "Los Angeles Chargers", yards: 17, aliases: ["Chargers", "San Diego Chargers"] },
        { name: "Tennessee Titans", yards: 17, aliases: ["Titans", "Houston Oilers", "Oilers"] },
        { name: "Carolina Panthers", yards: 14, aliases: ["Panthers", "Carolina"] },
        { name: "Jacksonville Jaguars", yards: 14, aliases: ["Jaguars", "Jags", "Jacksonville"] },
        { name: "Houston Texans", yards: 11, aliases: ["Texans"] },
        { name: "Atlanta Falcons", yards: 11, aliases: ["Falcons", "Atlanta"] },
        { name: "Minnesota Vikings", yards: 8, aliases: ["Vikings", "Minnesota"] },
        { name: "Cincinnati Bengals", yards: 8, aliases: ["Bengals", "Cincinnati"] },
        { name: "Detroit Lions", yards: 5, aliases: ["Lions", "Detroit"] },
        { name: "Cleveland Browns", yards: 2, aliases: ["Browns", "Cleveland"] },
        { name: "Buffalo Bills", yards: 2, aliases: ["Bills", "Buffalo"] },
      ],
    },
    {
      prompt: "Name a player selected first overall in the NFL Draft from 2015 through 2024.",
      answers: [
        { name: "Travon Walker", yards: 20 },
        { name: "Jameis Winston", yards: 17 },
        { name: "Jared Goff", yards: 14 },
        { name: "Myles Garrett", yards: 14 },
        { name: "Kyler Murray", yards: 11 },
        { name: "Bryce Young", yards: 8 },
        { name: "Baker Mayfield", yards: 8 },
        { name: "Trevor Lawrence", yards: 5 },
        { name: "Caleb Williams", yards: 5 },
        { name: "Joe Burrow", yards: 2 },
      ],
    },
    {
      prompt: "Name a player with a 2,000-yard regular-season rushing year (through 2024).",
      answers: [
        { name: "Jamal Lewis", yards: 20 },
        { name: "Terrell Davis", yards: 17 },
        { name: "Chris Johnson", yards: 14, aliases: ["CJ2K"] },
        { name: "O. J. Simpson", yards: 11, aliases: ["OJ Simpson", "OJ"] },
        { name: "Barry Sanders", yards: 8 },
        { name: "Adrian Peterson", yards: 5, aliases: ["AP", "All Day"] },
        { name: "Eric Dickerson", yards: 5 },
        { name: "Derrick Henry", yards: 2 },
        { name: "Saquon Barkley", yards: 2, aliases: ["Saquon"] },
      ],
    },
    {
      prompt: "Name an AP NFL MVP winner from the 2010 through 2024 seasons.",
      answers: [
        { name: "Matt Ryan", yards: 20 },
        { name: "Cam Newton", yards: 17 },
        { name: "Adrian Peterson", yards: 14, aliases: ["AP", "All Day"] },
        { name: "Peyton Manning", yards: 11, aliases: ["Peyton"] },
        { name: "Josh Allen", yards: 8 },
        { name: "Lamar Jackson", yards: 5, aliases: ["Lamar"] },
        { name: "Aaron Rodgers", yards: 5 },
        { name: "Tom Brady", yards: 2 },
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
      ],
    },
    {
      prompt: "Name a wide receiver who won Super Bowl MVP (through Super Bowl LIX).",
      answers: [
        { name: "Fred Biletnikoff", yards: 20 },
        { name: "Desmond Howard", yards: 20 },
        { name: "Deion Branch", yards: 17 },
        { name: "Lynn Swann", yards: 14 },
        { name: "Hines Ward", yards: 11 },
        { name: "Santonio Holmes", yards: 8 },
        { name: "Julian Edelman", yards: 5 },
        { name: "Jerry Rice", yards: 2 },
        { name: "Cooper Kupp", yards: 2 },
      ],
    },
  ],
  "2026-09-29": [
    {
      prompt: "Name a franchise with 4 or more Super Bowl wins (through Super Bowl LIX).",
      answers: [
        { name: "New York Giants", yards: 20, aliases: ["Giants"] },
        { name: "Green Bay Packers", yards: 17, aliases: ["Packers", "Green Bay"] },
        { name: "Kansas City Chiefs", yards: 8, aliases: ["Chiefs", "Kansas City"] },
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "San Francisco 49ers", yards: 14, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Pittsburgh Steelers", yards: 11, aliases: ["Steelers", "Pittsburgh"] },
        { name: "New England Patriots", yards: 5, aliases: ["Patriots", "Pats", "New England"] },
      ],
    },
    {
      prompt: "Name a player who won Super Bowl MVP more than once (through Super Bowl LIX).",
      answers: [
        { name: "Bart Starr", yards: 20 },
        { name: "Eli Manning", yards: 8, aliases: ["Eli"] },
        { name: "Terry Bradshaw", yards: 14 },
        { name: "Joe Montana", yards: 17 },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Tom Brady", yards: 2 },
      ],
    },
    {
      prompt: "Name a quarterback with a 5,000-yard passing season (through 2024).",
      answers: [
        { name: "Jameis Winston", yards: 14 },
        { name: "Matthew Stafford", yards: 8, aliases: ["Matt Stafford"] },
        { name: "Ben Roethlisberger", yards: 17, aliases: ["Big Ben"] },
        { name: "Justin Herbert", yards: 11 },
        { name: "Dan Marino", yards: 20 },
        { name: "Peyton Manning", yards: 8, aliases: ["Peyton"] },
        { name: "Tom Brady", yards: 2 },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Drew Brees", yards: 14 },
      ],
    },
    {
      prompt: "Name a head coach who won 2 or more Super Bowls (through Super Bowl LIX).",
      answers: [
        { name: "George Seifert", yards: 20 },
        { name: "Tom Flores", yards: 20 },
        { name: "Mike Shanahan", yards: 8 },
        { name: "Jimmy Johnson", yards: 5 },
        { name: "Tom Coughlin", yards: 14 },
        { name: "Joe Gibbs", yards: 8 },
        { name: "Don Shula", yards: 11 },
        { name: "Tom Landry", yards: 14 },
        { name: "Bill Parcells", yards: 11 },
        { name: "Bill Walsh", yards: 17 },
        { name: "Chuck Noll", yards: 17 },
        { name: "Vince Lombardi", yards: 5 },
        { name: "Andy Reid", yards: 2 },
        { name: "Bill Belichick", yards: 2 },
      ],
    },
    {
      prompt: "Name a player with a 20-sack season (official sacks, 1982–2024).",
      answers: [
        { name: "Chris Doleman", yards: 20 },
        { name: "Mark Gastineau", yards: 14 },
        { name: "Derrick Thomas", yards: 14 },
        { name: "Justin Houston", yards: 17 },
        { name: "Jared Allen", yards: 11 },
        { name: "DeMarcus Ware", yards: 17 },
        { name: "Reggie White", yards: 8 },
        { name: "Lawrence Taylor", yards: 8, aliases: ["LT"] },
        { name: "J. J. Watt", yards: 5, aliases: ["JJ Watt"] },
        { name: "T. J. Watt", yards: 5, aliases: ["TJ Watt"] },
        { name: "Michael Strahan", yards: 2 },
      ],
    },
  ],
  "2026-09-30": [
    {
      prompt: "Name an NFL team whose nickname is a bird.",
      answers: [
        { name: "Seattle Seahawks", yards: 2, aliases: ["Seahawks", "Seattle", "Hawks"] },
        { name: "Philadelphia Eagles", yards: 8, aliases: ["Eagles", "Philadelphia", "Philly"] },
        { name: "Baltimore Ravens", yards: 11, aliases: ["Ravens", "Baltimore"] },
        { name: "Arizona Cardinals", yards: 14, aliases: ["Cardinals", "Arizona"] },
        { name: "Atlanta Falcons", yards: 20, aliases: ["Falcons", "Atlanta"] },
      ],
    },
    {
      prompt: "Name a quarterback who started and won a Super Bowl from Super Bowl XXXV through LIX (2000–2024 seasons).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Aaron Rodgers", yards: 2 },
        { name: "Matthew Stafford", yards: 5, aliases: ["Matt Stafford"] },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Joe Flacco", yards: 8 },
        { name: "Russell Wilson", yards: 8, aliases: ["Russ"] },
        { name: "Peyton Manning", yards: 11, aliases: ["Peyton"] },
        { name: "Eli Manning", yards: 11, aliases: ["Eli"] },
        { name: "Jalen Hurts", yards: 14 },
        { name: "Drew Brees", yards: 14 },
        { name: "Ben Roethlisberger", yards: 17, aliases: ["Big Ben"] },
        { name: "Nick Foles", yards: 17 },
        { name: "Trent Dilfer", yards: 20 },
        { name: "Brad Johnson", yards: 20 },
      ],
    },
    {
      prompt: "Name a player with 15,000+ career rushing yards (through 2024).",
      answers: [
        { name: "Emmitt Smith", yards: 2, aliases: ["Emmitt"] },
        { name: "Walter Payton", yards: 8 },
        { name: "Barry Sanders", yards: 14 },
        { name: "Frank Gore", yards: 20 },
      ],
    },
    {
      prompt: "Name a player with 15,000+ career receiving yards (through 2024).",
      answers: [
        { name: "Randy Moss", yards: 2 },
        { name: "Jerry Rice", yards: 5 },
        { name: "Tony Gonzalez", yards: 8 },
        { name: "Larry Fitzgerald", yards: 14 },
        { name: "Terrell Owens", yards: 17, aliases: ["TO", "T.O."] },
        { name: "Isaac Bruce", yards: 20 },
      ],
    },
    {
      prompt: "Name a player with 150+ career sacks (official sacks, 1982–2024).",
      answers: [
        { name: "Reggie White", yards: 2 },
        { name: "Julius Peppers", yards: 8 },
        { name: "Bruce Smith", yards: 11 },
        { name: "Kevin Greene", yards: 14 },
        { name: "Chris Doleman", yards: 20 },
      ],
    },
  ],
  "2026-10-01": [
    {
      prompt: "Name a franchise that won back-to-back Super Bowls (through Super Bowl LIX).",
      answers: [
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "Kansas City Chiefs", yards: 5, aliases: ["Chiefs", "Kansas City"] },
        { name: "New England Patriots", yards: 8, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Green Bay Packers", yards: 11, aliases: ["Packers", "Green Bay"] },
        { name: "Pittsburgh Steelers", yards: 11, aliases: ["Steelers", "Pittsburgh"] },
        { name: "San Francisco 49ers", yards: 14, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Denver Broncos", yards: 17, aliases: ["Broncos", "Denver"] },
        { name: "Miami Dolphins", yards: 20, aliases: ["Dolphins", "Miami"] },
      ],
    },
    {
      prompt: "Name a player who won both the Heisman Trophy and Super Bowl MVP (through Super Bowl LIX).",
      answers: [
        { name: "Roger Staubach", yards: 2 },
        { name: "Jim Plunkett", yards: 8 },
        { name: "Desmond Howard", yards: 14 },
        { name: "Marcus Allen", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback taken first overall in the NFL Draft from 2000 through 2014.",
      answers: [
        { name: "Matthew Stafford", yards: 2, aliases: ["Matt Stafford"] },
        { name: "Cam Newton", yards: 5 },
        { name: "Eli Manning", yards: 5, aliases: ["Eli"] },
        { name: "Michael Vick", yards: 8, aliases: ["Vick"] },
        { name: "Andrew Luck", yards: 11 },
        { name: "Alex Smith", yards: 11 },
        { name: "JaMarcus Russell", yards: 14 },
        { name: "David Carr", yards: 17 },
        { name: "Sam Bradford", yards: 17 },
        { name: "Carson Palmer", yards: 20 },
      ],
    },
    {
      prompt: "Name a player who won AP Defensive Player of the Year more than once (through 2024).",
      answers: [
        { name: "Aaron Donald", yards: 2 },
        { name: "Ray Lewis", yards: 5 },
        { name: "J. J. Watt", yards: 8, aliases: ["JJ Watt"] },
        { name: "Lawrence Taylor", yards: 11, aliases: ["LT"] },
        { name: "Reggie White", yards: 11 },
        { name: "Joe Greene", yards: 14, aliases: ["Mean Joe Greene"] },
        { name: "Mike Singletary", yards: 17 },
        { name: "Bruce Smith", yards: 20 },
      ],
    },
    {
      prompt: "Name a player who won NFL MVP and Super Bowl MVP for the same season (through Super Bowl LIX).",
      answers: [
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
        { name: "Joe Montana", yards: 5 },
        { name: "Terry Bradshaw", yards: 8 },
        { name: "Kurt Warner", yards: 11 },
        { name: "Emmitt Smith", yards: 14 },
        { name: "Steve Young", yards: 17 },
        { name: "Bart Starr", yards: 20 },
      ],
    },
  ],
  "2026-10-02": [
    {
      prompt: "Name a franchise that has never played in a Super Bowl (through Super Bowl LIX).",
      answers: [
        { name: "Cleveland Browns", yards: 2, aliases: ["Browns", "Cleveland"] },
        { name: "Detroit Lions", yards: 8, aliases: ["Lions", "Detroit"] },
        { name: "Houston Texans", yards: 14, aliases: ["Texans", "Houston"] },
        { name: "Jacksonville Jaguars", yards: 20, aliases: ["Jaguars", "Jags", "Jacksonville"] },
      ],
    },
    {
      prompt: "Name a defensive player who won Super Bowl MVP (through Super Bowl LIX).",
      answers: [
        { name: "Ray Lewis", yards: 2 },
        { name: "Von Miller", yards: 5 },
        { name: "Malcolm Smith", yards: 5 },
        { name: "Randy White", yards: 8 },
        { name: "Chuck Howley", yards: 11 },
        { name: "Richard Dent", yards: 11 },
        { name: "Dexter Jackson", yards: 14 },
        { name: "Larry Brown", yards: 17 },
        { name: "Harvey Martin", yards: 17 },
        { name: "Jake Scott", yards: 20 },
      ],
    },
    {
      prompt: "Name a running back who won AP NFL MVP from 1990 through 2024.",
      answers: [
        { name: "Emmitt Smith", yards: 2, aliases: ["Emmitt"] },
        { name: "Adrian Peterson", yards: 5, aliases: ["AP", "All Day"] },
        { name: "Barry Sanders", yards: 8 },
        { name: "LaDainian Tomlinson", yards: 11, aliases: ["LT"] },
        { name: "Shaun Alexander", yards: 11 },
        { name: "Marshall Faulk", yards: 14 },
        { name: "Terrell Davis", yards: 17 },
        { name: "Thurman Thomas", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback with 500+ career touchdown passes (through 2024).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Aaron Rodgers", yards: 8 },
        { name: "Peyton Manning", yards: 11, aliases: ["Peyton"] },
        { name: "Drew Brees", yards: 14 },
        { name: "Brett Favre", yards: 20 },
      ],
    },
    {
      prompt: "Name a head coach who won both a college national championship and a Super Bowl (through Super Bowl LIX).",
      answers: [
        { name: "Pete Carroll", yards: 2 },
        { name: "Jimmy Johnson", yards: 11 },
        { name: "Barry Switzer", yards: 20 },
      ],
    },
  ],
  "2026-10-03": [
    {
      prompt: "Name a team that played its home games under a roof (dome or retractable) in the 2024 season.",
      answers: [
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "Detroit Lions", yards: 5, aliases: ["Lions", "Detroit"] },
        { name: "Las Vegas Raiders", yards: 5, aliases: ["Raiders", "Las Vegas"] },
        { name: "Minnesota Vikings", yards: 8, aliases: ["Vikings", "Minnesota"] },
        { name: "Arizona Cardinals", yards: 8, aliases: ["Cardinals", "Arizona"] },
        { name: "Los Angeles Rams", yards: 11, aliases: ["Rams", "LA Rams"] },
        { name: "Houston Texans", yards: 14, aliases: ["Texans", "Houston"] },
        { name: "Atlanta Falcons", yards: 14, aliases: ["Falcons", "Atlanta"] },
        { name: "Los Angeles Chargers", yards: 17, aliases: ["Chargers", "LA Chargers"] },
        { name: "Indianapolis Colts", yards: 17, aliases: ["Colts", "Indianapolis", "Indy"] },
        { name: "New Orleans Saints", yards: 20, aliases: ["Saints", "New Orleans"] },
      ],
    },
    {
      prompt: "Name a quarterback who started 4 or more Super Bowls (through Super Bowl LIX).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Peyton Manning", yards: 8, aliases: ["Peyton"] },
        { name: "John Elway", yards: 11 },
        { name: "Joe Montana", yards: 11 },
        { name: "Terry Bradshaw", yards: 14 },
        { name: "Roger Staubach", yards: 17 },
        { name: "Jim Kelly", yards: 20 },
      ],
    },
    {
      prompt: "Name a head coach who won a Super Bowl from Super Bowl XXXV through LIX (2000–2024 seasons).",
      answers: [
        { name: "Bill Belichick", yards: 2 },
        { name: "Mike Tomlin", yards: 2 },
        { name: "John Harbaugh", yards: 5 },
        { name: "Andy Reid", yards: 5 },
        { name: "Pete Carroll", yards: 8 },
        { name: "Mike McCarthy", yards: 8 },
        { name: "Sean Payton", yards: 8 },
        { name: "Jon Gruden", yards: 11 },
        { name: "Sean McVay", yards: 11 },
        { name: "Nick Sirianni", yards: 11 },
        { name: "Tony Dungy", yards: 14 },
        { name: "Gary Kubiak", yards: 14 },
        { name: "Bill Cowher", yards: 14 },
        { name: "Bruce Arians", yards: 17 },
        { name: "Doug Pederson", yards: 17 },
        { name: "Tom Coughlin", yards: 20 },
        { name: "Brian Billick", yards: 20 },
      ],
    },
    {
      prompt: "Name a head coach who took two different franchises to the Super Bowl (through Super Bowl LIX).",
      answers: [
        { name: "Andy Reid", yards: 2 },
        { name: "Bill Parcells", yards: 5 },
        { name: "Don Shula", yards: 8 },
        { name: "Dick Vermeil", yards: 11 },
        { name: "Dan Reeves", yards: 14 },
        { name: "Mike Holmgren", yards: 17 },
        { name: "John Fox", yards: 20 },
      ],
    },
    {
      prompt: "Name a franchise that won 2 or more Super Bowls from Super Bowl XXXV through LIX (2000–2024 seasons).",
      answers: [
        { name: "Philadelphia Eagles", yards: 2, aliases: ["Eagles", "Philadelphia", "Philly"] },
        { name: "New England Patriots", yards: 5, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Kansas City Chiefs", yards: 8, aliases: ["Chiefs", "Kansas City"] },
        { name: "Pittsburgh Steelers", yards: 11, aliases: ["Steelers", "Pittsburgh"] },
        { name: "New York Giants", yards: 14, aliases: ["Giants"] },
        { name: "Baltimore Ravens", yards: 17, aliases: ["Ravens", "Baltimore"] },
        { name: "Tampa Bay Buccaneers", yards: 20, aliases: ["Buccaneers", "Bucs", "Tampa Bay"] },
      ],
    },
  ],
};
