// One game per date (YYYY-MM-DD); this file is also the history of every past game.
// Each game is 5 prompts. Each answer is worth 2-20 yards (rarer = more yards).
// Optional "aliases" are other accepted spellings. A unique last name is accepted automatically.
const GAMES = {
  "2026-09-28": [
    {
      prompt: "Name a franchise that has never won a Super Bowl (through Super Bowl LIX).",
      answers: [
        { name: "Arizona Cardinals", yards: 20, aliases: ["Cardinals", "Arizona"] },
        { name: "Los Angeles Chargers", yards: 17, aliases: ["Chargers", "San Diego Chargers"] },
        { name: "Tennessee Titans", yards: 17, aliases: ["Titans", "Houston Oilers", "Oilers"] },
        { name: "Carolina Panthers", yards: 14, aliases: ["Panthers", "Carolina"] },
        { name: "Jacksonville Jaguars", yards: 14, aliases: ["Jaguars", "Jags", "Jacksonville"] },
        { name: "Houston Texans", yards: 11, aliases: ["Texans"] },
        { name: "Atlanta Falcons", yards: 11, aliases: ["Falcons", "Atlanta"] },
        { name: "Minnesota Vikings", yards: 8, aliases: ["Vikings", "Minnesota"] },
        { name: "Cincinnati Bengals", yards: 8, aliases: ["Bengals", "Cincinnati"] },
        { name: "Detroit Lions", yards: 5, aliases: ["Lions", "Detroit"] },
        { name: "Cleveland Browns", yards: 2, aliases: ["Browns", "Cleveland"] },
        { name: "Buffalo Bills", yards: 2, aliases: ["Bills", "Buffalo"] },
      ],
    },
    {
      prompt: "Name a player selected first overall in the NFL Draft from 2015 through 2024.",
      answers: [
        { name: "Travon Walker", yards: 20 },
        { name: "Jameis Winston", yards: 17 },
        { name: "Jared Goff", yards: 14 },
        { name: "Myles Garrett", yards: 14 },
        { name: "Kyler Murray", yards: 11 },
        { name: "Bryce Young", yards: 8 },
        { name: "Baker Mayfield", yards: 8 },
        { name: "Trevor Lawrence", yards: 5 },
        { name: "Caleb Williams", yards: 5 },
        { name: "Joe Burrow", yards: 2 },
      ],
    },
    {
      prompt: "Name a player with a 2,000-yard regular-season rushing year (through 2024).",
      answers: [
        { name: "Jamal Lewis", yards: 20 },
        { name: "Terrell Davis", yards: 17 },
        { name: "Chris Johnson", yards: 14, aliases: ["CJ2K"] },
        { name: "O. J. Simpson", yards: 11, aliases: ["OJ Simpson", "OJ"] },
        { name: "Barry Sanders", yards: 8 },
        { name: "Adrian Peterson", yards: 5, aliases: ["AP", "All Day"] },
        { name: "Eric Dickerson", yards: 5 },
        { name: "Derrick Henry", yards: 2 },
        { name: "Saquon Barkley", yards: 2, aliases: ["Saquon"] },
      ],
    },
    {
      prompt: "Name an AP NFL MVP winner from the 2010 through 2024 seasons.",
      answers: [
        { name: "Matt Ryan", yards: 20 },
        { name: "Cam Newton", yards: 17 },
        { name: "Adrian Peterson", yards: 14, aliases: ["AP", "All Day"] },
        { name: "Peyton Manning", yards: 11, aliases: ["Peyton"] },
        { name: "Josh Allen", yards: 8 },
        { name: "Lamar Jackson", yards: 5, aliases: ["Lamar"] },
        { name: "Aaron Rodgers", yards: 5 },
        { name: "Tom Brady", yards: 2 },
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
      ],
    },
    {
      prompt: "Name a wide receiver who won Super Bowl MVP (through Super Bowl LIX).",
      answers: [
        { name: "Fred Biletnikoff", yards: 20 },
        { name: "Desmond Howard", yards: 20 },
        { name: "Deion Branch", yards: 17 },
        { name: "Lynn Swann", yards: 14 },
        { name: "Hines Ward", yards: 11 },
        { name: "Santonio Holmes", yards: 8 },
        { name: "Julian Edelman", yards: 5 },
        { name: "Jerry Rice", yards: 2 },
        { name: "Cooper Kupp", yards: 2 },
      ],
    },
  ],
  "2026-09-29": [
    {
      prompt: "Name a franchise with 4 or more Super Bowl wins (through Super Bowl LIX).",
      answers: [
        { name: "New York Giants", yards: 20, aliases: ["Giants"] },
        { name: "Green Bay Packers", yards: 17, aliases: ["Packers", "Green Bay"] },
        { name: "Kansas City Chiefs", yards: 8, aliases: ["Chiefs", "Kansas City"] },
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "San Francisco 49ers", yards: 14, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Pittsburgh Steelers", yards: 11, aliases: ["Steelers", "Pittsburgh"] },
        { name: "New England Patriots", yards: 5, aliases: ["Patriots", "Pats", "New England"] },
      ],
    },
    {
      prompt: "Name a player who won Super Bowl MVP more than once (through Super Bowl LIX).",
      answers: [
        { name: "Bart Starr", yards: 20 },
        { name: "Eli Manning", yards: 8, aliases: ["Eli"] },
        { name: "Terry Bradshaw", yards: 14 },
        { name: "Joe Montana", yards: 17 },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Tom Brady", yards: 2 },
      ],
    },
    {
      prompt: "Name a quarterback with a 5,000-yard passing season (through 2024).",
      answers: [
        { name: "Jameis Winston", yards: 14 },
        { name: "Matthew Stafford", yards: 8, aliases: ["Matt Stafford"] },
        { name: "Ben Roethlisberger", yards: 17, aliases: ["Big Ben"] },
        { name: "Justin Herbert", yards: 11 },
        { name: "Dan Marino", yards: 20 },
        { name: "Peyton Manning", yards: 8, aliases: ["Peyton"] },
        { name: "Tom Brady", yards: 2 },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Drew Brees", yards: 14 },
      ],
    },
    {
      prompt: "Name a head coach who won 2 or more Super Bowls (through Super Bowl LIX).",
      answers: [
        { name: "George Seifert", yards: 20 },
        { name: "Tom Flores", yards: 20 },
        { name: "Mike Shanahan", yards: 8 },
        { name: "Jimmy Johnson", yards: 5 },
        { name: "Tom Coughlin", yards: 14 },
        { name: "Joe Gibbs", yards: 8 },
        { name: "Don Shula", yards: 11 },
        { name: "Tom Landry", yards: 14 },
        { name: "Bill Parcells", yards: 11 },
        { name: "Bill Walsh", yards: 17 },
        { name: "Chuck Noll", yards: 17 },
        { name: "Vince Lombardi", yards: 5 },
        { name: "Andy Reid", yards: 2 },
        { name: "Bill Belichick", yards: 2 },
      ],
    },
    {
      prompt: "Name a player with a 20-sack season (official sacks, 1982–2024).",
      answers: [
        { name: "Chris Doleman", yards: 20 },
        { name: "Mark Gastineau", yards: 14 },
        { name: "Derrick Thomas", yards: 14 },
        { name: "Justin Houston", yards: 17 },
        { name: "Jared Allen", yards: 11 },
        { name: "DeMarcus Ware", yards: 17 },
        { name: "Reggie White", yards: 8 },
        { name: "Lawrence Taylor", yards: 8, aliases: ["LT"] },
        { name: "J. J. Watt", yards: 5, aliases: ["JJ Watt"] },
        { name: "T. J. Watt", yards: 5, aliases: ["TJ Watt"] },
        { name: "Michael Strahan", yards: 2 },
      ],
    },
  ],
  "2026-09-30": [
    {
      prompt: "Name an NFL team whose nickname is a bird.",
      answers: [
        { name: "Seattle Seahawks", yards: 2, aliases: ["Seahawks", "Seattle", "Hawks"] },
        { name: "Philadelphia Eagles", yards: 8, aliases: ["Eagles", "Philadelphia", "Philly"] },
        { name: "Baltimore Ravens", yards: 11, aliases: ["Ravens", "Baltimore"] },
        { name: "Arizona Cardinals", yards: 14, aliases: ["Cardinals", "Arizona"] },
        { name: "Atlanta Falcons", yards: 20, aliases: ["Falcons", "Atlanta"] },
      ],
    },
    {
      prompt: "Name a quarterback who started and won a Super Bowl from Super Bowl XXXV through LIX (2000–2024 seasons).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Aaron Rodgers", yards: 2 },
        { name: "Matthew Stafford", yards: 5, aliases: ["Matt Stafford"] },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Joe Flacco", yards: 8 },
        { name: "Russell Wilson", yards: 8, aliases: ["Russ"] },
        { name: "Peyton Manning", yards: 11, aliases: ["Peyton"] },
        { name: "Eli Manning", yards: 11, aliases: ["Eli"] },
        { name: "Jalen Hurts", yards: 14 },
        { name: "Drew Brees", yards: 14 },
        { name: "Ben Roethlisberger", yards: 17, aliases: ["Big Ben"] },
        { name: "Nick Foles", yards: 17 },
        { name: "Trent Dilfer", yards: 20 },
        { name: "Brad Johnson", yards: 20 },
      ],
    },
    {
      prompt: "Name a player with 15,000+ career rushing yards (through 2024).",
      answers: [
        { name: "Emmitt Smith", yards: 2, aliases: ["Emmitt"] },
        { name: "Walter Payton", yards: 8 },
        { name: "Barry Sanders", yards: 14 },
        { name: "Frank Gore", yards: 20 },
      ],
    },
    {
      prompt: "Name a player with 15,000+ career receiving yards (through 2024).",
      answers: [
        { name: "Randy Moss", yards: 2 },
        { name: "Jerry Rice", yards: 5 },
        { name: "Tony Gonzalez", yards: 8 },
        { name: "Larry Fitzgerald", yards: 14 },
        { name: "Terrell Owens", yards: 17, aliases: ["TO", "T.O."] },
        { name: "Isaac Bruce", yards: 20 },
      ],
    },
    {
      prompt: "Name a player with 150+ career sacks (official sacks, 1982–2024).",
      answers: [
        { name: "Reggie White", yards: 2 },
        { name: "Julius Peppers", yards: 8 },
        { name: "Bruce Smith", yards: 11 },
        { name: "Kevin Greene", yards: 14 },
        { name: "Chris Doleman", yards: 20 },
      ],
    },
  ],
  "2026-10-01": [
    {
      prompt: "Name a franchise that won back-to-back Super Bowls (through Super Bowl LIX).",
      answers: [
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "Kansas City Chiefs", yards: 5, aliases: ["Chiefs", "Kansas City"] },
        { name: "New England Patriots", yards: 8, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Green Bay Packers", yards: 11, aliases: ["Packers", "Green Bay"] },
        { name: "Pittsburgh Steelers", yards: 11, aliases: ["Steelers", "Pittsburgh"] },
        { name: "San Francisco 49ers", yards: 14, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Denver Broncos", yards: 17, aliases: ["Broncos", "Denver"] },
        { name: "Miami Dolphins", yards: 20, aliases: ["Dolphins", "Miami"] },
      ],
    },
    {
      prompt: "Name a player who won both the Heisman Trophy and Super Bowl MVP (through Super Bowl LIX).",
      answers: [
        { name: "Roger Staubach", yards: 2 },
        { name: "Jim Plunkett", yards: 8 },
        { name: "Desmond Howard", yards: 14 },
        { name: "Marcus Allen", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback taken first overall in the NFL Draft from 2000 through 2014.",
      answers: [
        { name: "Matthew Stafford", yards: 2, aliases: ["Matt Stafford"] },
        { name: "Cam Newton", yards: 5 },
        { name: "Eli Manning", yards: 5, aliases: ["Eli"] },
        { name: "Michael Vick", yards: 8, aliases: ["Vick"] },
        { name: "Andrew Luck", yards: 11 },
        { name: "Alex Smith", yards: 11 },
        { name: "JaMarcus Russell", yards: 14 },
        { name: "David Carr", yards: 17 },
        { name: "Sam Bradford", yards: 17 },
        { name: "Carson Palmer", yards: 20 },
      ],
    },
    {
      prompt: "Name a player who won AP Defensive Player of the Year more than once (through 2024).",
      answers: [
        { name: "Aaron Donald", yards: 2 },
        { name: "Ray Lewis", yards: 5 },
        { name: "J. J. Watt", yards: 8, aliases: ["JJ Watt"] },
        { name: "Lawrence Taylor", yards: 11, aliases: ["LT"] },
        { name: "Reggie White", yards: 11 },
        { name: "Joe Greene", yards: 14, aliases: ["Mean Joe Greene"] },
        { name: "Mike Singletary", yards: 17 },
        { name: "Bruce Smith", yards: 20 },
      ],
    },
    {
      prompt: "Name a player who won NFL MVP and Super Bowl MVP for the same season (through Super Bowl LIX).",
      answers: [
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
        { name: "Joe Montana", yards: 5 },
        { name: "Terry Bradshaw", yards: 8 },
        { name: "Kurt Warner", yards: 11 },
        { name: "Emmitt Smith", yards: 14 },
        { name: "Steve Young", yards: 17 },
        { name: "Bart Starr", yards: 20 },
      ],
    },
  ],
  "2026-10-02": [
    {
      prompt: "Name a franchise that has won a Super Bowl (through Super Bowl LIX).",
      answers: [
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "Chicago Bears", yards: 2, aliases: ["Bears", "Chicago"] },
        { name: "Seattle Seahawks", yards: 5, aliases: ["Seahawks", "Seattle"] },
        { name: "New England Patriots", yards: 5, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Kansas City Chiefs", yards: 5, aliases: ["Chiefs", "Kansas City"] },
        { name: "Philadelphia Eagles", yards: 8, aliases: ["Eagles", "Philadelphia", "Philly"] },
        { name: "Green Bay Packers", yards: 8, aliases: ["Packers", "Green Bay"] },
        { name: "Pittsburgh Steelers", yards: 8, aliases: ["Steelers", "Pittsburgh"] },
        { name: "San Francisco 49ers", yards: 11, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Washington Commanders", yards: 11, aliases: ["Commanders", "Washington", "Redskins", "Washington Redskins", "Washington Football Team"] },
        { name: "Denver Broncos", yards: 11, aliases: ["Broncos", "Denver"] },
        { name: "New York Giants", yards: 11, aliases: ["Giants"] },
        { name: "Miami Dolphins", yards: 14, aliases: ["Dolphins", "Miami"] },
        { name: "Los Angeles Rams", yards: 14, aliases: ["Rams", "St. Louis Rams", "LA Rams"] },
        { name: "Baltimore Ravens", yards: 14, aliases: ["Ravens", "Baltimore"] },
        { name: "Las Vegas Raiders", yards: 17, aliases: ["Raiders", "Oakland Raiders", "Los Angeles Raiders"] },
        { name: "Tampa Bay Buccaneers", yards: 17, aliases: ["Buccaneers", "Bucs", "Tampa Bay"] },
        { name: "New York Jets", yards: 17, aliases: ["Jets"] },
        { name: "New Orleans Saints", yards: 20, aliases: ["Saints", "New Orleans"] },
        { name: "Indianapolis Colts", yards: 20, aliases: ["Colts", "Baltimore Colts", "Indianapolis", "Indy"] },
      ],
    },
    {
      prompt: "Name a quarterback drafted in the first round from 2018 through 2021.",
      answers: [
        { name: "Josh Allen", yards: 2 },
        { name: "Joe Burrow", yards: 2 },
        { name: "Baker Mayfield", yards: 5, aliases: ["Baker"] },
        { name: "Lamar Jackson", yards: 5, aliases: ["Lamar"] },
        { name: "Sam Darnold", yards: 8 },
        { name: "Justin Herbert", yards: 8 },
        { name: "Tua Tagovailoa", yards: 8, aliases: ["Tua"] },
        { name: "Kyler Murray", yards: 11 },
        { name: "Trevor Lawrence", yards: 11 },
        { name: "Jordan Love", yards: 11 },
        { name: "Justin Fields", yards: 14 },
        { name: "Mac Jones", yards: 14 },
        { name: "Daniel Jones", yards: 14 },
        { name: "Zach Wilson", yards: 17 },
        { name: "Trey Lance", yards: 17 },
        { name: "Josh Rosen", yards: 20 },
        { name: "Dwayne Haskins", yards: 20 },
      ],
    },
    {
      prompt: "Name an AP NFL MVP from 1990 through 2024.",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Aaron Rodgers", yards: 2 },
        { name: "Josh Allen", yards: 5 },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Peyton Manning", yards: 5, aliases: ["Peyton"] },
        { name: "Lamar Jackson", yards: 5, aliases: ["Lamar"] },
        { name: "Cam Newton", yards: 8 },
        { name: "Joe Montana", yards: 8 },
        { name: "Brett Favre", yards: 8 },
        { name: "Kurt Warner", yards: 11 },
        { name: "Emmitt Smith", yards: 11, aliases: ["Emmitt"] },
        { name: "Adrian Peterson", yards: 11, aliases: ["AP", "All Day"] },
        { name: "Barry Sanders", yards: 11 },
        { name: "Matt Ryan", yards: 14 },
        { name: "Steve Young", yards: 14 },
        { name: "Steve McNair", yards: 14 },
        { name: "Shaun Alexander", yards: 17 },
        { name: "LaDainian Tomlinson", yards: 17, aliases: ["LT"] },
        { name: "Terrell Davis", yards: 17 },
        { name: "Marshall Faulk", yards: 17 },
        { name: "Rich Gannon", yards: 20 },
        { name: "Thurman Thomas", yards: 20 },
      ],
    },
    {
      prompt: "Name a college that produced the #1 overall pick in an NFL Draft from 2000 through 2024.",
      answers: [
        { name: "Alabama", yards: 2, aliases: ["Bama"] },
        { name: "Michigan", yards: 2, not: ["Michigan State"] },
        { name: "LSU", yards: 5, aliases: ["Louisiana State"] },
        { name: "Penn State", yards: 5, aliases: ["PSU"] },
        { name: "Georgia", yards: 5, aliases: ["UGA"] },
        { name: "Ole Miss", yards: 8, aliases: ["Mississippi"] },
        { name: "Auburn", yards: 8 },
        { name: "USC", yards: 8, aliases: ["Southern California", "Southern Cal", "Trojans"] },
        { name: "Oklahoma", yards: 11, aliases: ["OU"] },
        { name: "Clemson", yards: 11 },
        { name: "Texas A&M", yards: 11, aliases: ["A&M", "TAMU"] },
        { name: "Cal", yards: 11, aliases: ["California", "Berkeley", "Cal Berkeley"] },
        { name: "Florida State", yards: 14, aliases: ["FSU"] },
        { name: "South Carolina", yards: 14, not: ["North Carolina", "UNC"] },
        { name: "Utah", yards: 14 },
        { name: "Stanford", yards: 17 },
        { name: "Virginia Tech", yards: 17, aliases: ["VT"] },
        { name: "NC State", yards: 17, aliases: ["North Carolina State"] },
        { name: "Fresno State", yards: 20 },
        { name: "Central Michigan", yards: 20, aliases: ["CMU"] },
      ],
    },
    {
      prompt: "Name a quarterback with 50,000+ career passing yards (through 2024).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Aaron Rodgers", yards: 5 },
        { name: "Matthew Stafford", yards: 5, aliases: ["Matt Stafford"] },
        { name: "Peyton Manning", yards: 8, aliases: ["Peyton"] },
        { name: "Philip Rivers", yards: 8 },
        { name: "Eli Manning", yards: 11, aliases: ["Eli"] },
        { name: "Brett Favre", yards: 11 },
        { name: "Drew Brees", yards: 14 },
        { name: "Ben Roethlisberger", yards: 14, aliases: ["Big Ben"] },
        { name: "John Elway", yards: 17 },
        { name: "Dan Marino", yards: 17 },
        { name: "Matt Ryan", yards: 20 },
      ],
    },
  ],
  "2026-10-03": [
    {
      prompt: "Name a franchise that has lost a Super Bowl (through Super Bowl LIX).",
      answers: [
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "Chicago Bears", yards: 2, aliases: ["Bears", "Chicago"] },
        { name: "Buffalo Bills", yards: 5, aliases: ["Bills", "Buffalo"] },
        { name: "Seattle Seahawks", yards: 5, aliases: ["Seahawks", "Seattle"] },
        { name: "New England Patriots", yards: 5, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Kansas City Chiefs", yards: 5, aliases: ["Chiefs", "Kansas City"] },
        { name: "Philadelphia Eagles", yards: 8, aliases: ["Eagles", "Philadelphia", "Philly"] },
        { name: "Green Bay Packers", yards: 8, aliases: ["Packers", "Green Bay"] },
        { name: "Pittsburgh Steelers", yards: 8, aliases: ["Steelers", "Pittsburgh"] },
        { name: "San Francisco 49ers", yards: 8, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Denver Broncos", yards: 11, aliases: ["Broncos", "Denver"] },
        { name: "Washington Commanders", yards: 11, aliases: ["Commanders", "Washington", "Redskins", "Washington Redskins", "Washington Football Team"] },
        { name: "Miami Dolphins", yards: 11, aliases: ["Dolphins", "Miami"] },
        { name: "New York Giants", yards: 11, aliases: ["Giants"] },
        { name: "Los Angeles Rams", yards: 14, aliases: ["Rams", "St. Louis Rams", "LA Rams"] },
        { name: "Minnesota Vikings", yards: 14, aliases: ["Vikings", "Minnesota"] },
        { name: "Las Vegas Raiders", yards: 14, aliases: ["Raiders", "Oakland Raiders", "Los Angeles Raiders"] },
        { name: "Arizona Cardinals", yards: 14, aliases: ["Cardinals", "Arizona"] },
        { name: "Carolina Panthers", yards: 17, aliases: ["Panthers", "Carolina"] },
        { name: "Atlanta Falcons", yards: 17, aliases: ["Falcons", "Atlanta"] },
        { name: "Tennessee Titans", yards: 17, aliases: ["Titans", "Tennessee"] },
        { name: "Cincinnati Bengals", yards: 17, aliases: ["Bengals", "Cincinnati"] },
        { name: "Los Angeles Chargers", yards: 20, aliases: ["Chargers", "San Diego Chargers", "LA Chargers"] },
        { name: "Indianapolis Colts", yards: 20, aliases: ["Colts", "Baltimore Colts", "Indianapolis", "Indy"] },
      ],
    },
    {
      prompt: "Name an AP Offensive Rookie of the Year from 2000 through 2024.",
      answers: [
        { name: "Odell Beckham Jr.", yards: 2, aliases: ["OBJ", "Odell"] },
        { name: "Cam Newton", yards: 2 },
        { name: "Justin Herbert", yards: 2 },
        { name: "Jayden Daniels", yards: 5 },
        { name: "Dak Prescott", yards: 5, aliases: ["Dak"] },
        { name: "Saquon Barkley", yards: 5, aliases: ["Saquon"] },
        { name: "Kyler Murray", yards: 8 },
        { name: "C. J. Stroud", yards: 8, aliases: ["CJ Stroud"] },
        { name: "Ben Roethlisberger", yards: 8, aliases: ["Big Ben"] },
        { name: "Ja'Marr Chase", yards: 8 },
        { name: "Adrian Peterson", yards: 8, aliases: ["AP", "All Day"] },
        { name: "Matt Ryan", yards: 11 },
        { name: "Alvin Kamara", yards: 11 },
        { name: "Robert Griffin III", yards: 11, aliases: ["RG3", "RGIII"] },
        { name: "Vince Young", yards: 14 },
        { name: "Garrett Wilson", yards: 14 },
        { name: "Todd Gurley", yards: 14 },
        { name: "Sam Bradford", yards: 14 },
        { name: "Eddie Lacy", yards: 14 },
        { name: "Anquan Boldin", yards: 17 },
        { name: "Clinton Portis", yards: 17 },
        { name: "Percy Harvin", yards: 17 },
        { name: "Cadillac Williams", yards: 20, aliases: ["Carnell Williams"] },
        { name: "Mike Anderson", yards: 20 },
        { name: "Anthony Thomas", yards: 20 },
      ],
    },
    {
      prompt: "Name a non-quarterback drafted #1 overall from 1990 through 2024.",
      answers: [
        { name: "Myles Garrett", yards: 2 },
        { name: "Jadeveon Clowney", yards: 2, aliases: ["Clowney"] },
        { name: "Travon Walker", yards: 5 },
        { name: "Keyshawn Johnson", yards: 8, aliases: ["Keyshawn"] },
        { name: "Mario Williams", yards: 8 },
        { name: "Eric Fisher", yards: 8 },
        { name: "Jake Long", yards: 11 },
        { name: "Orlando Pace", yards: 14 },
        { name: "Ki-Jana Carter", yards: 14 },
        { name: "Steve Emtman", yards: 14 },
        { name: "Russell Maryland", yards: 17 },
        { name: "Courtney Brown", yards: 20 },
        { name: "Dan Wilkinson", yards: 20, aliases: ["Big Daddy Wilkinson"] },
      ],
    },
    {
      prompt: "Name a head coach who won a Super Bowl from Super Bowl XXXV through LIX (2000–2024 seasons).",
      answers: [
        { name: "Bill Belichick", yards: 2 },
        { name: "Mike Tomlin", yards: 2 },
        { name: "John Harbaugh", yards: 5 },
        { name: "Andy Reid", yards: 5 },
        { name: "Pete Carroll", yards: 8 },
        { name: "Mike McCarthy", yards: 8 },
        { name: "Sean Payton", yards: 8 },
        { name: "Jon Gruden", yards: 11 },
        { name: "Sean McVay", yards: 11 },
        { name: "Nick Sirianni", yards: 11 },
        { name: "Tony Dungy", yards: 14 },
        { name: "Gary Kubiak", yards: 14 },
        { name: "Bill Cowher", yards: 14 },
        { name: "Bruce Arians", yards: 17 },
        { name: "Doug Pederson", yards: 17 },
        { name: "Tom Coughlin", yards: 20 },
        { name: "Brian Billick", yards: 20 },
      ],
    },
    {
      prompt: "Name a team that played its home games under a roof (dome or retractable) in the 2024 season.",
      answers: [
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "Detroit Lions", yards: 5, aliases: ["Lions", "Detroit"] },
        { name: "Las Vegas Raiders", yards: 5, aliases: ["Raiders", "Las Vegas"] },
        { name: "Minnesota Vikings", yards: 8, aliases: ["Vikings", "Minnesota"] },
        { name: "Arizona Cardinals", yards: 8, aliases: ["Cardinals", "Arizona"] },
        { name: "Los Angeles Rams", yards: 11, aliases: ["Rams", "LA Rams"] },
        { name: "Houston Texans", yards: 14, aliases: ["Texans", "Houston"] },
        { name: "Atlanta Falcons", yards: 14, aliases: ["Falcons", "Atlanta"] },
        { name: "Los Angeles Chargers", yards: 17, aliases: ["Chargers", "LA Chargers"] },
        { name: "Indianapolis Colts", yards: 17, aliases: ["Colts", "Indianapolis", "Indy"] },
        { name: "New Orleans Saints", yards: 20, aliases: ["Saints", "New Orleans"] },
      ],
    },
  ],
  "2026-10-04": [
    {
      prompt: "Name an NFL team whose nickname is an animal.",
      answers: [
        { name: "Chicago Bears", yards: 2, aliases: ["Bears", "Chicago"] },
        { name: "Seattle Seahawks", yards: 2, aliases: ["Seahawks", "Seattle"] },
        { name: "Philadelphia Eagles", yards: 5, aliases: ["Eagles", "Philadelphia", "Philly"] },
        { name: "Denver Broncos", yards: 5, aliases: ["Broncos", "Denver"] },
        { name: "Detroit Lions", yards: 8, aliases: ["Lions", "Detroit"] },
        { name: "Miami Dolphins", yards: 8, aliases: ["Dolphins", "Miami"] },
        { name: "Baltimore Ravens", yards: 11, aliases: ["Ravens", "Baltimore"] },
        { name: "Los Angeles Rams", yards: 11, aliases: ["Rams", "LA Rams"] },
        { name: "Arizona Cardinals", yards: 14, aliases: ["Cardinals", "Arizona"] },
        { name: "Carolina Panthers", yards: 14, aliases: ["Panthers", "Carolina"] },
        { name: "Atlanta Falcons", yards: 17, aliases: ["Falcons", "Atlanta"] },
        { name: "Indianapolis Colts", yards: 17, aliases: ["Colts", "Indianapolis", "Indy"] },
        { name: "Jacksonville Jaguars", yards: 20, aliases: ["Jaguars", "Jags", "Jacksonville"] },
        { name: "Cincinnati Bengals", yards: 20, aliases: ["Bengals", "Cincinnati"] },
      ],
    },
    {
      prompt: "Name a Super Bowl MVP from Super Bowl XXXV through LIX (2000–2024 seasons).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Aaron Rodgers", yards: 2 },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Peyton Manning", yards: 5, aliases: ["Peyton"] },
        { name: "Joe Flacco", yards: 5 },
        { name: "Jalen Hurts", yards: 8 },
        { name: "Eli Manning", yards: 8, aliases: ["Eli"] },
        { name: "Cooper Kupp", yards: 8, aliases: ["Kupp"] },
        { name: "Drew Brees", yards: 11 },
        { name: "Ray Lewis", yards: 11 },
        { name: "Von Miller", yards: 14 },
        { name: "Julian Edelman", yards: 14, aliases: ["Edelman"] },
        { name: "Nick Foles", yards: 14 },
        { name: "Hines Ward", yards: 17 },
        { name: "Santonio Holmes", yards: 17 },
        { name: "Deion Branch", yards: 17 },
        { name: "Malcolm Smith", yards: 20 },
        { name: "Dexter Jackson", yards: 20 },
      ],
    },
    {
      prompt: "Name a franchise that held the #1 overall pick in an NFL Draft from 2000 through 2024.",
      answers: [
        { name: "Chicago Bears", yards: 2, aliases: ["Bears", "Chicago"] },
        { name: "Kansas City Chiefs", yards: 2, aliases: ["Chiefs", "Kansas City"] },
        { name: "Cleveland Browns", yards: 5, aliases: ["Browns", "Cleveland"] },
        { name: "Detroit Lions", yards: 5, aliases: ["Lions", "Detroit"] },
        { name: "San Francisco 49ers", yards: 8, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Tampa Bay Buccaneers", yards: 8, aliases: ["Buccaneers", "Bucs", "Tampa Bay"] },
        { name: "Miami Dolphins", yards: 8, aliases: ["Dolphins", "Miami"] },
        { name: "Los Angeles Rams", yards: 11, aliases: ["Rams", "St. Louis Rams", "LA Rams"] },
        { name: "Las Vegas Raiders", yards: 11, aliases: ["Raiders", "Oakland Raiders"] },
        { name: "Arizona Cardinals", yards: 11, aliases: ["Cardinals", "Arizona"] },
        { name: "Houston Texans", yards: 14, aliases: ["Texans", "Houston"] },
        { name: "Carolina Panthers", yards: 14, aliases: ["Panthers", "Carolina"] },
        { name: "Atlanta Falcons", yards: 14, aliases: ["Falcons", "Atlanta"] },
        { name: "Los Angeles Chargers", yards: 17, aliases: ["Chargers", "San Diego Chargers", "LA Chargers"] },
        { name: "Cincinnati Bengals", yards: 17, aliases: ["Bengals", "Cincinnati"] },
        { name: "Indianapolis Colts", yards: 20, aliases: ["Colts", "Indianapolis", "Indy"] },
        { name: "Jacksonville Jaguars", yards: 20, aliases: ["Jaguars", "Jags", "Jacksonville"] },
      ],
    },
    {
      prompt: "Name a quarterback with a 40+ touchdown pass season (through 2024).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Aaron Rodgers", yards: 5 },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Matthew Stafford", yards: 8, aliases: ["Matt Stafford"] },
        { name: "Russell Wilson", yards: 8, aliases: ["Russ"] },
        { name: "Joe Burrow", yards: 11 },
        { name: "Peyton Manning", yards: 11, aliases: ["Peyton"] },
        { name: "Lamar Jackson", yards: 14, aliases: ["Lamar"] },
        { name: "Kurt Warner", yards: 14 },
        { name: "Drew Brees", yards: 17 },
        { name: "Andrew Luck", yards: 17 },
        { name: "Dan Marino", yards: 20 },
      ],
    },
    {
      prompt: "Name an AP Defensive Player of the Year from 2000 through 2024.",
      answers: [
        { name: "Myles Garrett", yards: 2 },
        { name: "Aaron Donald", yards: 2 },
        { name: "Ray Lewis", yards: 5 },
        { name: "J. J. Watt", yards: 5, aliases: ["JJ Watt"] },
        { name: "T. J. Watt", yards: 5, aliases: ["TJ Watt"] },
        { name: "Nick Bosa", yards: 8 },
        { name: "Michael Strahan", yards: 8 },
        { name: "Troy Polamalu", yards: 8 },
        { name: "Luke Kuechly", yards: 11 },
        { name: "Khalil Mack", yards: 11 },
        { name: "Charles Woodson", yards: 11 },
        { name: "Patrick Surtain II", yards: 11, aliases: ["Patrick Surtain"] },
        { name: "Jason Taylor", yards: 14 },
        { name: "Ed Reed", yards: 14 },
        { name: "Stephon Gilmore", yards: 14 },
        { name: "James Harrison", yards: 17 },
        { name: "Brian Urlacher", yards: 17 },
        { name: "Terrell Suggs", yards: 17 },
        { name: "Derrick Brooks", yards: 20 },
        { name: "Bob Sanders", yards: 20 },
      ],
    },
  ],
  "2026-10-05": [
    {
      prompt: "Name a team in the AFC (2024 season).",
      answers: [
        { name: "Buffalo Bills", yards: 2, aliases: ["Bills", "Buffalo"] },
        { name: "Kansas City Chiefs", yards: 2, aliases: ["Chiefs", "Kansas City"] },
        { name: "Pittsburgh Steelers", yards: 5, aliases: ["Steelers", "Pittsburgh"] },
        { name: "New England Patriots", yards: 5, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Denver Broncos", yards: 8, aliases: ["Broncos", "Denver"] },
        { name: "Cleveland Browns", yards: 8, aliases: ["Browns", "Cleveland"] },
        { name: "Miami Dolphins", yards: 8, aliases: ["Dolphins", "Miami"] },
        { name: "Las Vegas Raiders", yards: 11, aliases: ["Raiders", "Oakland Raiders", "Las Vegas"] },
        { name: "Baltimore Ravens", yards: 11, aliases: ["Ravens", "Baltimore"] },
        { name: "New York Jets", yards: 14, aliases: ["Jets"] },
        { name: "Houston Texans", yards: 14, aliases: ["Texans", "Houston"] },
        { name: "Tennessee Titans", yards: 14, aliases: ["Titans", "Tennessee", "Oilers"] },
        { name: "Los Angeles Chargers", yards: 17, aliases: ["Chargers", "San Diego Chargers", "LA Chargers"] },
        { name: "Cincinnati Bengals", yards: 17, aliases: ["Bengals", "Cincinnati"] },
        { name: "Jacksonville Jaguars", yards: 20, aliases: ["Jaguars", "Jags", "Jacksonville"] },
        { name: "Indianapolis Colts", yards: 20, aliases: ["Colts", "Indianapolis", "Indy"] },
      ],
    },
    {
      prompt: "Name an AP Defensive Rookie of the Year from 2005 through 2024.",
      answers: [
        { name: "Aaron Donald", yards: 2 },
        { name: "Micah Parsons", yards: 2 },
        { name: "Von Miller", yards: 5 },
        { name: "Sauce Gardner", yards: 5, aliases: ["Ahmad Gardner"] },
        { name: "Nick Bosa", yards: 5 },
        { name: "Luke Kuechly", yards: 8 },
        { name: "Joey Bosa", yards: 8 },
        { name: "DeMeco Ryans", yards: 8 },
        { name: "Will Anderson Jr.", yards: 11, aliases: ["Will Anderson"] },
        { name: "Chase Young", yards: 11 },
        { name: "Jared Verse", yards: 11 },
        { name: "Jerod Mayo", yards: 11 },
        { name: "Ndamukong Suh", yards: 14, aliases: ["Suh"] },
        { name: "Marshon Lattimore", yards: 14 },
        { name: "Brian Cushing", yards: 14 },
        { name: "Patrick Willis", yards: 17 },
        { name: "Shaquille Leonard", yards: 17, aliases: ["Darius Leonard"] },
        { name: "Shawne Merriman", yards: 17 },
        { name: "Marcus Peters", yards: 20 },
        { name: "Sheldon Richardson", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback who started and lost a Super Bowl from Super Bowl XXXV through LIX (2000–2024 seasons).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
        { name: "Russell Wilson", yards: 5, aliases: ["Russ"] },
        { name: "Joe Burrow", yards: 5 },
        { name: "Peyton Manning", yards: 5, aliases: ["Peyton"] },
        { name: "Jalen Hurts", yards: 8 },
        { name: "Cam Newton", yards: 8 },
        { name: "Brock Purdy", yards: 8 },
        { name: "Colin Kaepernick", yards: 11, aliases: ["Kaepernick"] },
        { name: "Jared Goff", yards: 11 },
        { name: "Kurt Warner", yards: 11 },
        { name: "Jimmy Garoppolo", yards: 11, aliases: ["Jimmy G"] },
        { name: "Ben Roethlisberger", yards: 14, aliases: ["Big Ben"] },
        { name: "Matt Ryan", yards: 14 },
        { name: "Donovan McNabb", yards: 14 },
        { name: "Rich Gannon", yards: 17 },
        { name: "Matt Hasselbeck", yards: 17 },
        { name: "Rex Grossman", yards: 17 },
        { name: "Kerry Collins", yards: 20 },
        { name: "Jake Delhomme", yards: 20 },
      ],
    },
    {
      prompt: "Name a Madden NFL cover star from Madden NFL 10 through Madden NFL 26.",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Josh Allen", yards: 2 },
        { name: "Patrick Mahomes", yards: 5, aliases: ["Mahomes"] },
        { name: "Christian McCaffrey", yards: 5, aliases: ["CMC"] },
        { name: "Odell Beckham Jr.", yards: 5, aliases: ["OBJ", "Odell"] },
        { name: "Lamar Jackson", yards: 8, aliases: ["Lamar"] },
        { name: "Rob Gronkowski", yards: 8, aliases: ["Gronk"] },
        { name: "Antonio Brown", yards: 8, aliases: ["AB"] },
        { name: "Saquon Barkley", yards: 11, aliases: ["Saquon"] },
        { name: "Drew Brees", yards: 11 },
        { name: "John Madden", yards: 11 },
        { name: "Adrian Peterson", yards: 14, aliases: ["AP", "All Day"] },
        { name: "Larry Fitzgerald", yards: 14 },
        { name: "Barry Sanders", yards: 14 },
        { name: "Richard Sherman", yards: 17 },
        { name: "Calvin Johnson", yards: 17, aliases: ["Megatron"] },
        { name: "Terrell Owens", yards: 17, aliases: ["TO", "T.O."] },
        { name: "Troy Polamalu", yards: 20 },
        { name: "Peyton Hillis", yards: 20 },
      ],
    },
    {
      prompt: "Name an AP Offensive Player of the Year from 2000 through 2024.",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
        { name: "Christian McCaffrey", yards: 5, aliases: ["CMC"] },
        { name: "Peyton Manning", yards: 5, aliases: ["Peyton"] },
        { name: "Derrick Henry", yards: 5 },
        { name: "Cam Newton", yards: 8 },
        { name: "Saquon Barkley", yards: 8, aliases: ["Saquon"] },
        { name: "Justin Jefferson", yards: 8 },
        { name: "Cooper Kupp", yards: 8, aliases: ["Kupp"] },
        { name: "Drew Brees", yards: 11 },
        { name: "Adrian Peterson", yards: 11, aliases: ["AP", "All Day"] },
        { name: "Matt Ryan", yards: 11 },
        { name: "Chris Johnson", yards: 14, aliases: ["CJ2K"] },
        { name: "Shaun Alexander", yards: 14 },
        { name: "Michael Thomas", yards: 14 },
        { name: "LaDainian Tomlinson", yards: 14, aliases: ["LT"] },
        { name: "Todd Gurley", yards: 17 },
        { name: "Marshall Faulk", yards: 17 },
        { name: "Jamal Lewis", yards: 17 },
        { name: "DeMarco Murray", yards: 20 },
        { name: "Priest Holmes", yards: 20 },
      ],
    },
  ],
  "2026-10-06": [
    {
      prompt: "Name a team in the NFC (2024 season).",
      answers: [
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "Chicago Bears", yards: 2, aliases: ["Bears", "Chicago"] },
        { name: "Seattle Seahawks", yards: 5, aliases: ["Seahawks", "Seattle"] },
        { name: "Philadelphia Eagles", yards: 5, aliases: ["Eagles", "Philadelphia", "Philly"] },
        { name: "Green Bay Packers", yards: 8, aliases: ["Packers", "Green Bay"] },
        { name: "Detroit Lions", yards: 8, aliases: ["Lions", "Detroit"] },
        { name: "Washington Commanders", yards: 8, aliases: ["Commanders", "Washington", "Redskins", "Washington Redskins", "Washington Football Team"] },
        { name: "San Francisco 49ers", yards: 11, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Los Angeles Rams", yards: 11, aliases: ["Rams", "St. Louis Rams", "LA Rams"] },
        { name: "New York Giants", yards: 14, aliases: ["Giants"] },
        { name: "Minnesota Vikings", yards: 14, aliases: ["Vikings", "Minnesota"] },
        { name: "Tampa Bay Buccaneers", yards: 14, aliases: ["Buccaneers", "Bucs", "Tampa Bay"] },
        { name: "Arizona Cardinals", yards: 17, aliases: ["Cardinals", "Arizona"] },
        { name: "Carolina Panthers", yards: 17, aliases: ["Panthers", "Carolina"] },
        { name: "Atlanta Falcons", yards: 20, aliases: ["Falcons", "Atlanta"] },
        { name: "New Orleans Saints", yards: 20, aliases: ["Saints", "New Orleans"] },
      ],
    },
    {
      prompt: "Name a player who led the NFL in rushing yards in a season from 2000 through 2024.",
      answers: [
        { name: "Christian McCaffrey", yards: 2, aliases: ["CMC"] },
        { name: "Derrick Henry", yards: 2 },
        { name: "Saquon Barkley", yards: 5, aliases: ["Saquon"] },
        { name: "Ezekiel Elliott", yards: 5, aliases: ["Zeke"] },
        { name: "Adrian Peterson", yards: 5, aliases: ["AP", "All Day"] },
        { name: "Josh Jacobs", yards: 8 },
        { name: "Chris Johnson", yards: 8, aliases: ["CJ2K"] },
        { name: "LaDainian Tomlinson", yards: 8, aliases: ["LT"] },
        { name: "Kareem Hunt", yards: 11 },
        { name: "Shaun Alexander", yards: 11 },
        { name: "Ricky Williams", yards: 11 },
        { name: "Jonathan Taylor", yards: 11 },
        { name: "LeSean McCoy", yards: 14, aliases: ["Shady McCoy"] },
        { name: "Arian Foster", yards: 14 },
        { name: "Edgerrin James", yards: 14, aliases: ["Edge"] },
        { name: "DeMarco Murray", yards: 17 },
        { name: "Jamal Lewis", yards: 17 },
        { name: "Priest Holmes", yards: 17 },
        { name: "Maurice Jones-Drew", yards: 20, aliases: ["MJD"] },
        { name: "Curtis Martin", yards: 20 },
      ],
    },
    {
      prompt: "Name a head coach who lost a Super Bowl from Super Bowl XXXV through LIX (2000–2024 seasons).",
      answers: [
        { name: "Bill Belichick", yards: 2 },
        { name: "Jim Harbaugh", yards: 2 },
        { name: "Mike Tomlin", yards: 5 },
        { name: "Pete Carroll", yards: 5 },
        { name: "Andy Reid", yards: 5 },
        { name: "Sean McVay", yards: 8 },
        { name: "Kyle Shanahan", yards: 8 },
        { name: "Nick Sirianni", yards: 8 },
        { name: "Dan Quinn", yards: 11 },
        { name: "Zac Taylor", yards: 11 },
        { name: "Ron Rivera", yards: 11 },
        { name: "Lovie Smith", yards: 14 },
        { name: "Mike Holmgren", yards: 14 },
        { name: "Bill Callahan", yards: 14 },
        { name: "John Fox", yards: 17 },
        { name: "Jim Caldwell", yards: 17 },
        { name: "Mike Martz", yards: 17 },
        { name: "Ken Whisenhunt", yards: 20 },
        { name: "Jim Fassel", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback drafted in the first round from 2010 through 2014.",
      answers: [
        { name: "Cam Newton", yards: 2 },
        { name: "Tim Tebow", yards: 2 },
        { name: "Johnny Manziel", yards: 5, aliases: ["Johnny Football"] },
        { name: "Andrew Luck", yards: 5 },
        { name: "Robert Griffin III", yards: 8, aliases: ["RG3", "RGIII"] },
        { name: "Teddy Bridgewater", yards: 8 },
        { name: "Ryan Tannehill", yards: 11 },
        { name: "Sam Bradford", yards: 11 },
        { name: "Blake Bortles", yards: 14 },
        { name: "Christian Ponder", yards: 14 },
        { name: "Blaine Gabbert", yards: 17 },
        { name: "EJ Manuel", yards: 17 },
        { name: "Brandon Weeden", yards: 20 },
        { name: "Jake Locker", yards: 20 },
      ],
    },
    {
      prompt: "Name a headliner of a Super Bowl halftime show from 2010 through 2025.",
      answers: [
        { name: "Lady Gaga", yards: 2 },
        { name: "Jennifer Lopez", yards: 2, aliases: ["J.Lo", "JLo"] },
        { name: "Rihanna", yards: 5 },
        { name: "Eminem", yards: 5 },
        { name: "Madonna", yards: 5 },
        { name: "Beyoncé", yards: 8, aliases: ["Beyonce"] },
        { name: "Shakira", yards: 8 },
        { name: "Bruno Mars", yards: 8 },
        { name: "Katy Perry", yards: 11 },
        { name: "Snoop Dogg", yards: 11, aliases: ["Snoop"] },
        { name: "Kendrick Lamar", yards: 11, aliases: ["Kendrick"] },
        { name: "The Weeknd", yards: 11, aliases: ["Weeknd"] },
        { name: "Justin Timberlake", yards: 14 },
        { name: "Usher", yards: 14 },
        { name: "Dr. Dre", yards: 14 },
        { name: "Coldplay", yards: 17 },
        { name: "The Who", yards: 17 },
        { name: "Mary J. Blige", yards: 17 },
        { name: "Black Eyed Peas", yards: 20 },
        { name: "Maroon 5", yards: 20 },
      ],
    },
  ],
  "2026-10-07": [
    {
      prompt: "Name a franchise that won the AFC Championship from the 1990 through 2024 seasons.",
      answers: [
        { name: "Buffalo Bills", yards: 2, aliases: ["Bills", "Buffalo"] },
        { name: "Kansas City Chiefs", yards: 5, aliases: ["Chiefs", "Kansas City"] },
        { name: "New England Patriots", yards: 5, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Pittsburgh Steelers", yards: 8, aliases: ["Steelers", "Pittsburgh"] },
        { name: "Denver Broncos", yards: 8, aliases: ["Broncos", "Denver"] },
        { name: "Baltimore Ravens", yards: 11, aliases: ["Ravens", "Baltimore"] },
        { name: "Las Vegas Raiders", yards: 14, aliases: ["Raiders", "Oakland Raiders", "Las Vegas"] },
        { name: "Tennessee Titans", yards: 14, aliases: ["Titans", "Tennessee", "Oilers"] },
        { name: "Cincinnati Bengals", yards: 17, aliases: ["Bengals", "Cincinnati"] },
        { name: "Los Angeles Chargers", yards: 17, aliases: ["Chargers", "San Diego Chargers", "LA Chargers"] },
        { name: "Indianapolis Colts", yards: 20, aliases: ["Colts", "Indianapolis", "Indy"] },
      ],
    },
    {
      prompt: "Name a player who led the NFL in receiving yards in a season from 2000 through 2024.",
      answers: [
        { name: "Stefon Diggs", yards: 2 },
        { name: "Tyreek Hill", yards: 2 },
        { name: "Antonio Brown", yards: 5, aliases: ["AB"] },
        { name: "Cooper Kupp", yards: 5, aliases: ["Kupp"] },
        { name: "Justin Jefferson", yards: 5 },
        { name: "Ja'Marr Chase", yards: 8 },
        { name: "Chad Johnson", yards: 8, aliases: ["Ochocinco", "Chad Ochocinco"] },
        { name: "Julio Jones", yards: 8 },
        { name: "Calvin Johnson", yards: 11, aliases: ["Megatron"] },
        { name: "Michael Thomas", yards: 11 },
        { name: "Steve Smith", yards: 11 },
        { name: "Josh Gordon", yards: 11 },
        { name: "Marvin Harrison", yards: 14 },
        { name: "T. Y. Hilton", yards: 14, aliases: ["TY Hilton"] },
        { name: "Andre Johnson", yards: 14 },
        { name: "Reggie Wayne", yards: 17 },
        { name: "Torry Holt", yards: 17 },
        { name: "Muhsin Muhammad", yards: 17 },
        { name: "David Boston", yards: 20 },
        { name: "Brandon Lloyd", yards: 20 },
      ],
    },
    {
      prompt: "Name an AP Coach of the Year from 2005 through 2024.",
      answers: [
        { name: "Bill Belichick", yards: 2 },
        { name: "Mike Vrabel", yards: 2 },
        { name: "Jim Harbaugh", yards: 5 },
        { name: "John Harbaugh", yards: 5 },
        { name: "Sean Payton", yards: 8 },
        { name: "Sean McVay", yards: 8 },
        { name: "Kevin Stefanski", yards: 8 },
        { name: "Brian Daboll", yards: 11 },
        { name: "Matt Nagy", yards: 11 },
        { name: "Jason Garrett", yards: 14 },
        { name: "Bruce Arians", yards: 14 },
        { name: "Kevin O'Connell", yards: 14 },
        { name: "Ron Rivera", yards: 17 },
        { name: "Lovie Smith", yards: 17 },
        { name: "Marvin Lewis", yards: 20 },
        { name: "Mike Smith", yards: 20 },
      ],
    },
    {
      prompt: "Name a wide receiver drafted in the first round in 2020 or 2021.",
      answers: [
        { name: "Justin Jefferson", yards: 2 },
        { name: "Henry Ruggs", yards: 5 },
        { name: "Ja'Marr Chase", yards: 5 },
        { name: "CeeDee Lamb", yards: 8 },
        { name: "Brandon Aiyuk", yards: 8 },
        { name: "DeVonta Smith", yards: 11 },
        { name: "Jaylen Waddle", yards: 14 },
        { name: "Kadarius Toney", yards: 14 },
        { name: "Jerry Jeudy", yards: 17 },
        { name: "Jalen Reagor", yards: 17 },
        { name: "Rashod Bateman", yards: 20 },
      ],
    },
    {
      prompt: "Name a Heisman Trophy winner from 2000 through 2024.",
      answers: [
        { name: "Baker Mayfield", yards: 2, aliases: ["Baker"] },
        { name: "Joe Burrow", yards: 2 },
        { name: "Caleb Williams", yards: 2 },
        { name: "Lamar Jackson", yards: 5, aliases: ["Lamar"] },
        { name: "Cam Newton", yards: 5 },
        { name: "Derrick Henry", yards: 5 },
        { name: "Jayden Daniels", yards: 8 },
        { name: "Kyler Murray", yards: 8 },
        { name: "Tim Tebow", yards: 8 },
        { name: "Bryce Young", yards: 8 },
        { name: "Travis Hunter", yards: 8 },
        { name: "Johnny Manziel", yards: 11, aliases: ["Johnny Football"] },
        { name: "Jameis Winston", yards: 11 },
        { name: "DeVonta Smith", yards: 11 },
        { name: "Marcus Mariota", yards: 14 },
        { name: "Matt Leinart", yards: 14 },
        { name: "Reggie Bush", yards: 14 },
        { name: "Robert Griffin III", yards: 14, aliases: ["RG3", "RGIII"] },
        { name: "Sam Bradford", yards: 14 },
        { name: "Carson Palmer", yards: 17 },
        { name: "Mark Ingram", yards: 17 },
        { name: "Chris Weinke", yards: 17 },
        { name: "Troy Smith", yards: 20 },
        { name: "Jason White", yards: 20 },
        { name: "Eric Crouch", yards: 20 },
      ],
    },
  ],
  "2026-10-08": [
    {
      prompt: "Name a wide receiver drafted in the first round from 2014 through 2016.",
      answers: [
        { name: "Odell Beckham Jr.", yards: 2, aliases: ["OBJ", "Odell"] },
        { name: "Mike Evans", yards: 2 },
        { name: "Brandin Cooks", yards: 5 },
        { name: "Amari Cooper", yards: 5 },
        { name: "Nelson Agholor", yards: 8 },
        { name: "Sammy Watkins", yards: 8 },
        { name: "Corey Coleman", yards: 11 },
        { name: "Laquon Treadwell", yards: 11 },
        { name: "DeVante Parker", yards: 11 },
        { name: "Kevin White", yards: 14 },
        { name: "Will Fuller", yards: 14 },
        { name: "Kelvin Benjamin", yards: 17 },
        { name: "Phillip Dorsett", yards: 17 },
        { name: "Breshad Perriman", yards: 20 },
        { name: "Josh Doctson", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback who led the NFL in passing yards in a season from 2000 through 2024.",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
        { name: "Joe Burrow", yards: 5 },
        { name: "Peyton Manning", yards: 5, aliases: ["Peyton"] },
        { name: "Philip Rivers", yards: 8 },
        { name: "Tua Tagovailoa", yards: 8, aliases: ["Tua"] },
        { name: "Deshaun Watson", yards: 11 },
        { name: "Drew Brees", yards: 11 },
        { name: "Kurt Warner", yards: 14 },
        { name: "Jameis Winston", yards: 14 },
        { name: "Ben Roethlisberger", yards: 17, aliases: ["Big Ben"] },
        { name: "Rich Gannon", yards: 17 },
        { name: "Daunte Culpepper", yards: 20 },
        { name: "Matt Schaub", yards: 20 },
      ],
    },
    {
      prompt: "Name an AP Comeback Player of the Year from 2010 through 2024.",
      answers: [
        { name: "Matthew Stafford", yards: 2, aliases: ["Matt Stafford"] },
        { name: "Peyton Manning", yards: 2, aliases: ["Peyton"] },
        { name: "Joe Burrow", yards: 5 },
        { name: "Philip Rivers", yards: 5 },
        { name: "Joe Flacco", yards: 8 },
        { name: "Rob Gronkowski", yards: 8, aliases: ["Gronk"] },
        { name: "Geno Smith", yards: 11 },
        { name: "Michael Vick", yards: 11, aliases: ["Vick"] },
        { name: "Keenan Allen", yards: 14 },
        { name: "Andrew Luck", yards: 14 },
        { name: "Alex Smith", yards: 17 },
        { name: "Ryan Tannehill", yards: 17 },
        { name: "Jordy Nelson", yards: 20 },
        { name: "Eric Berry", yards: 20 },
      ],
    },
    {
      prompt: "Name a running back drafted in the first round from 2015 through 2024.",
      answers: [
        { name: "Christian McCaffrey", yards: 2, aliases: ["CMC"] },
        { name: "Saquon Barkley", yards: 2, aliases: ["Saquon"] },
        { name: "Ezekiel Elliott", yards: 5, aliases: ["Zeke"] },
        { name: "Jahmyr Gibbs", yards: 5 },
        { name: "Josh Jacobs", yards: 8 },
        { name: "Bijan Robinson", yards: 8, aliases: ["Bijan"] },
        { name: "Travis Etienne", yards: 11 },
        { name: "Najee Harris", yards: 11 },
        { name: "Todd Gurley", yards: 14 },
        { name: "Leonard Fournette", yards: 14 },
        { name: "Clyde Edwards-Helaire", yards: 17, aliases: ["CEH"] },
        { name: "Sony Michel", yards: 17 },
        { name: "Rashaad Penny", yards: 20 },
        { name: "Melvin Gordon", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback who started and won a Super Bowl AND started and lost one (through Super Bowl LIX).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
        { name: "Russell Wilson", yards: 5, aliases: ["Russ"] },
        { name: "Peyton Manning", yards: 8, aliases: ["Peyton"] },
        { name: "Jalen Hurts", yards: 8 },
        { name: "John Elway", yards: 8 },
        { name: "Brett Favre", yards: 11 },
        { name: "Kurt Warner", yards: 14 },
        { name: "Ben Roethlisberger", yards: 14, aliases: ["Big Ben"] },
        { name: "Roger Staubach", yards: 14 },
        { name: "Joe Theismann", yards: 17 },
        { name: "Len Dawson", yards: 20 },
        { name: "Bob Griese", yards: 20 },
      ],
    },
  ],
  "2026-10-09": [
    {
      prompt: "Name a franchise that played in a Super Bowl after the 1990 through 1999 seasons (Super Bowls XXV–XXXIV).",
      answers: [
        { name: "Dallas Cowboys", yards: 2, aliases: ["Cowboys", "Dallas"] },
        { name: "New England Patriots", yards: 2, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Buffalo Bills", yards: 5, aliases: ["Bills", "Buffalo"] },
        { name: "Green Bay Packers", yards: 8, aliases: ["Packers", "Green Bay"] },
        { name: "Pittsburgh Steelers", yards: 8, aliases: ["Steelers", "Pittsburgh"] },
        { name: "San Francisco 49ers", yards: 8, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Denver Broncos", yards: 11, aliases: ["Broncos", "Denver"] },
        { name: "Los Angeles Rams", yards: 14, aliases: ["Rams", "St. Louis Rams", "LA Rams"] },
        { name: "New York Giants", yards: 14, aliases: ["Giants"] },
        { name: "Washington Commanders", yards: 14, aliases: ["Commanders", "Washington", "Redskins", "Washington Redskins", "Washington Football Team"] },
        { name: "Atlanta Falcons", yards: 17, aliases: ["Falcons", "Atlanta"] },
        { name: "Tennessee Titans", yards: 20, aliases: ["Titans", "Tennessee", "Oilers"] },
        { name: "Los Angeles Chargers", yards: 20, aliases: ["Chargers", "San Diego Chargers", "LA Chargers"] },
      ],
    },
    {
      prompt: "Name a player who led the NFL in sacks in a season from 2000 through 2024.",
      answers: [
        { name: "Aaron Donald", yards: 2 },
        { name: "J. J. Watt", yards: 2, aliases: ["JJ Watt"] },
        { name: "Michael Strahan", yards: 5 },
        { name: "T. J. Watt", yards: 5, aliases: ["TJ Watt"] },
        { name: "Nick Bosa", yards: 5 },
        { name: "Chandler Jones", yards: 8 },
        { name: "Trey Hendrickson", yards: 8 },
        { name: "Jason Taylor", yards: 8 },
        { name: "Jared Allen", yards: 11 },
        { name: "DeMarcus Ware", yards: 11 },
        { name: "Shaquil Barrett", yards: 11 },
        { name: "Shawne Merriman", yards: 14 },
        { name: "Dwight Freeney", yards: 14 },
        { name: "Justin Houston", yards: 14 },
        { name: "Robert Mathis", yards: 17 },
        { name: "Vic Beasley", yards: 17 },
        { name: "Elvis Dumervil", yards: 17 },
        { name: "La'Roi Glover", yards: 20 },
        { name: "Derrick Burgess", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback drafted in the first round from 2005 through 2009.",
      answers: [
        { name: "Aaron Rodgers", yards: 2 },
        { name: "Matthew Stafford", yards: 2, aliases: ["Matt Stafford"] },
        { name: "Joe Flacco", yards: 5 },
        { name: "Mark Sanchez", yards: 8 },
        { name: "Matt Ryan", yards: 8 },
        { name: "Jay Cutler", yards: 8 },
        { name: "Vince Young", yards: 11 },
        { name: "Alex Smith", yards: 14 },
        { name: "Matt Leinart", yards: 14 },
        { name: "JaMarcus Russell", yards: 14 },
        { name: "Brady Quinn", yards: 17 },
        { name: "Josh Freeman", yards: 20 },
        { name: "Jason Campbell", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback who started a playoff game in the 2024 season.",
      answers: [
        { name: "Josh Allen", yards: 2 },
        { name: "Patrick Mahomes", yards: 2, aliases: ["Mahomes"] },
        { name: "Russell Wilson", yards: 5, aliases: ["Russ"] },
        { name: "Matthew Stafford", yards: 5, aliases: ["Matt Stafford"] },
        { name: "Lamar Jackson", yards: 8, aliases: ["Lamar"] },
        { name: "Baker Mayfield", yards: 8, aliases: ["Baker"] },
        { name: "Sam Darnold", yards: 11 },
        { name: "Jalen Hurts", yards: 11 },
        { name: "Bo Nix", yards: 14 },
        { name: "Justin Herbert", yards: 14 },
        { name: "Jayden Daniels", yards: 17 },
        { name: "Jordan Love", yards: 17 },
        { name: "C. J. Stroud", yards: 20, aliases: ["CJ Stroud"] },
        { name: "Jared Goff", yards: 20 },
      ],
    },
    {
      prompt: "Name an NFC head coach in Week 1 of the 2024 season.",
      answers: [
        { name: "Mike McCarthy", yards: 2 },
        { name: "Sean McVay", yards: 2 },
        { name: "Dan Campbell", yards: 5 },
        { name: "Matt LaFleur", yards: 5 },
        { name: "Mike Macdonald", yards: 8 },
        { name: "Brian Daboll", yards: 8 },
        { name: "Kyle Shanahan", yards: 8 },
        { name: "Nick Sirianni", yards: 11 },
        { name: "Raheem Morris", yards: 11 },
        { name: "Dan Quinn", yards: 14 },
        { name: "Jonathan Gannon", yards: 14 },
        { name: "Todd Bowles", yards: 14 },
        { name: "Matt Eberflus", yards: 17 },
        { name: "Kevin O'Connell", yards: 17 },
        { name: "Dave Canales", yards: 20 },
        { name: "Dennis Allen", yards: 20 },
      ],
    },
  ],
  "2026-10-10": [
    {
      prompt: "Name a quarterback who won Super Bowl MVP from Super Bowl I through XXXIV.",
      answers: [
        { name: "Troy Aikman", yards: 2 },
        { name: "Joe Montana", yards: 2 },
        { name: "Terry Bradshaw", yards: 5 },
        { name: "John Elway", yards: 5 },
        { name: "Kurt Warner", yards: 8 },
        { name: "Joe Namath", yards: 8, aliases: ["Broadway Joe"] },
        { name: "Steve Young", yards: 11 },
        { name: "Roger Staubach", yards: 11 },
        { name: "Doug Williams", yards: 14 },
        { name: "Phil Simms", yards: 14 },
        { name: "Jim Plunkett", yards: 17 },
        { name: "Bart Starr", yards: 17 },
        { name: "Len Dawson", yards: 20 },
        { name: "Mark Rypien", yards: 20 },
      ],
    },
    {
      prompt: "Name a tight end drafted in the first round from 2010 through 2024.",
      answers: [
        { name: "Brock Bowers", yards: 2 },
        { name: "Kyle Pitts", yards: 5 },
        { name: "David Njoku", yards: 5 },
        { name: "T. J. Hockenson", yards: 8, aliases: ["TJ Hockenson"] },
        { name: "Dalton Kincaid", yards: 8 },
        { name: "Evan Engram", yards: 11 },
        { name: "Noah Fant", yards: 11 },
        { name: "Hayden Hurst", yards: 14 },
        { name: "Eric Ebron", yards: 14 },
        { name: "O. J. Howard", yards: 17, aliases: ["OJ Howard"] },
        { name: "Tyler Eifert", yards: 17 },
        { name: "Jermaine Gresham", yards: 20 },
      ],
    },
    {
      prompt: "Name a head coach of the Dallas Cowboys (all time, through 2025).",
      answers: [
        { name: "Mike McCarthy", yards: 2 },
        { name: "Jimmy Johnson", yards: 5 },
        { name: "Bill Parcells", yards: 5 },
        { name: "Brian Schottenheimer", yards: 8 },
        { name: "Jason Garrett", yards: 11 },
        { name: "Tom Landry", yards: 11 },
        { name: "Barry Switzer", yards: 14 },
        { name: "Wade Phillips", yards: 17 },
        { name: "Chan Gailey", yards: 17 },
        { name: "Dave Campo", yards: 20 },
      ],
    },
    {
      prompt: "Name a wide receiver drafted in the first round in 2022 or 2023.",
      answers: [
        { name: "Jaxon Smith-Njigba", yards: 2, aliases: ["JSN"] },
        { name: "Jameson Williams", yards: 5 },
        { name: "Zay Flowers", yards: 5 },
        { name: "Chris Olave", yards: 8 },
        { name: "Garrett Wilson", yards: 11 },
        { name: "Drake London", yards: 11 },
        { name: "Jordan Addison", yards: 14 },
        { name: "Treylon Burks", yards: 17 },
        { name: "Jahan Dotson", yards: 17 },
        { name: "Quentin Johnston", yards: 20 },
      ],
    },
    {
      prompt: "Name a running back inducted into the Pro Football Hall of Fame from 2003 through 2025.",
      answers: [
        { name: "Emmitt Smith", yards: 2, aliases: ["Emmitt"] },
        { name: "Barry Sanders", yards: 5 },
        { name: "LaDainian Tomlinson", yards: 5, aliases: ["LT"] },
        { name: "Marshall Faulk", yards: 8 },
        { name: "Jerome Bettis", yards: 8, aliases: ["The Bus"] },
        { name: "Terrell Davis", yards: 11 },
        { name: "Marcus Allen", yards: 11 },
        { name: "Edgerrin James", yards: 14, aliases: ["Edge"] },
        { name: "Thurman Thomas", yards: 14 },
        { name: "Curtis Martin", yards: 17 },
        { name: "Fritz Pollard", yards: 17 },
        { name: "Floyd Little", yards: 20 },
      ],
    },
  ],
  "2026-10-11": [
    {
      prompt: "Name a franchise that played in a Super Bowl after the 1980 through 1989 seasons (Super Bowls XV–XXIV).",
      answers: [
        { name: "Chicago Bears", yards: 2, aliases: ["Bears", "Chicago"] },
        { name: "New England Patriots", yards: 5, aliases: ["Patriots", "Pats", "New England"] },
        { name: "Philadelphia Eagles", yards: 5, aliases: ["Eagles", "Philadelphia", "Philly"] },
        { name: "San Francisco 49ers", yards: 8, aliases: ["49ers", "Niners", "San Francisco"] },
        { name: "Washington Commanders", yards: 11, aliases: ["Commanders", "Washington", "Redskins", "Washington Redskins", "Washington Football Team"] },
        { name: "Miami Dolphins", yards: 11, aliases: ["Dolphins", "Miami"] },
        { name: "Denver Broncos", yards: 14, aliases: ["Broncos", "Denver"] },
        { name: "New York Giants", yards: 17, aliases: ["Giants"] },
        { name: "Las Vegas Raiders", yards: 17, aliases: ["Raiders", "Oakland Raiders", "Las Vegas"] },
        { name: "Cincinnati Bengals", yards: 20, aliases: ["Bengals", "Cincinnati"] },
      ],
    },
    {
      prompt: "Name a player drafted in the top 3 from 2017 through 2021.",
      answers: [
        { name: "Baker Mayfield", yards: 2, aliases: ["Baker"] },
        { name: "Joe Burrow", yards: 2 },
        { name: "Sam Darnold", yards: 5 },
        { name: "Myles Garrett", yards: 5 },
        { name: "Kyler Murray", yards: 8 },
        { name: "Saquon Barkley", yards: 8, aliases: ["Saquon"] },
        { name: "Trevor Lawrence", yards: 11 },
        { name: "Nick Bosa", yards: 11 },
        { name: "Zach Wilson", yards: 11 },
        { name: "Trey Lance", yards: 14 },
        { name: "Mitchell Trubisky", yards: 14, aliases: ["Mitch Trubisky"] },
        { name: "Quinnen Williams", yards: 17 },
        { name: "Chase Young", yards: 17 },
        { name: "Jeff Okudah", yards: 20 },
        { name: "Solomon Thomas", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback drafted in the first round from 2022 through 2024.",
      answers: [
        { name: "Drake Maye", yards: 2 },
        { name: "Caleb Williams", yards: 5 },
        { name: "Bo Nix", yards: 5 },
        { name: "Jayden Daniels", yards: 8 },
        { name: "J. J. McCarthy", yards: 11, aliases: ["JJ McCarthy"] },
        { name: "C. J. Stroud", yards: 11, aliases: ["CJ Stroud"] },
        { name: "Bryce Young", yards: 14 },
        { name: "Michael Penix Jr.", yards: 17, aliases: ["Michael Penix"] },
        { name: "Kenny Pickett", yards: 17 },
        { name: "Anthony Richardson", yards: 20 },
      ],
    },
    {
      prompt: "Name an AFC head coach in Week 1 of the 2024 season.",
      answers: [
        { name: "Mike Tomlin", yards: 2 },
        { name: "Jim Harbaugh", yards: 2 },
        { name: "Mike McDaniel", yards: 5 },
        { name: "John Harbaugh", yards: 5 },
        { name: "Sean Payton", yards: 8 },
        { name: "Andy Reid", yards: 8 },
        { name: "Robert Saleh", yards: 8 },
        { name: "Kevin Stefanski", yards: 11 },
        { name: "Sean McDermott", yards: 11 },
        { name: "DeMeco Ryans", yards: 14 },
        { name: "Jerod Mayo", yards: 14 },
        { name: "Brian Callahan", yards: 14 },
        { name: "Zac Taylor", yards: 17 },
        { name: "Doug Pederson", yards: 17 },
        { name: "Shane Steichen", yards: 20 },
        { name: "Antonio Pierce", yards: 20 },
      ],
    },
    {
      prompt: "Name a quarterback who was NOT a first-round pick but started and won a Super Bowl (through Super Bowl LIX).",
      answers: [
        { name: "Tom Brady", yards: 2, aliases: ["Brady"] },
        { name: "Russell Wilson", yards: 2, aliases: ["Russ"] },
        { name: "Jalen Hurts", yards: 5 },
        { name: "Joe Montana", yards: 5 },
        { name: "Drew Brees", yards: 8 },
        { name: "Brett Favre", yards: 8 },
        { name: "Kurt Warner", yards: 8 },
        { name: "Nick Foles", yards: 11 },
        { name: "Roger Staubach", yards: 11 },
        { name: "Johnny Unitas", yards: 14 },
        { name: "Ken Stabler", yards: 14, aliases: ["Kenny Stabler"] },
        { name: "Joe Theismann", yards: 14 },
        { name: "Brad Johnson", yards: 17 },
        { name: "Bart Starr", yards: 17 },
        { name: "Mark Rypien", yards: 20 },
        { name: "Jeff Hostetler", yards: 20 },
      ],
    },
  ],
};
